* Library Information
 /org-table-jb-extras.el/ --- Extra commands & functions for working with org-tables

 - Filename :: [[file:org-table-jb-extras.el][org-table-jb-extras.el]]
 - Description :: Extra commands & functions for working with org-tables
 - Author :: Joe Bloggs <vapniks@yahoo.com>
 - Maintainer :: Joe Bloggs <vapniks@yahoo.com>
Copyleft (Ↄ) 2024, Joe Bloggs, all rites reversed.
 - Created :: 2024-05-23 22:44:11
 - Version :: 20240523.2317
 - Last-Updated :: Thu May 23 23:17:48 2024
 -           By :: Joe Bloggs
 -     Update # :: 1
 - URL :: https://github.com/vapniks/org-table-jb-extras
 - Keywords :: tools 
 - Compatibility :: GNU Emacs 25.2.2
 - Package-Requires :: ((org "9.4.6") (cl-lib "1") (ido-choose-function "0.1") (dash "2.19.1") (s "1.13.1"))

* Possible Dependencies

org-mode cl-lib ido-choose-function ampl-mode dash s 

* Commentary

Bitcoin donations gratefully accepted: 16xSxS5v7rpknr4WL8unwCRab5nZEfc7eK

This library contains many extra functions & commands for dealing with org-tables which are documented below.
Most of the functions useful to users can be accessed through a single command: *org-table-dispatch*.
When *org-table-dispatch* is called while point is in an org-table an ido menu of possible
actions from *org-table-dispatch-actions* is offered to the user. These actions include:
"copy table", "copy rectangle", "kill/clear cells", "export to file", "copy cols to calc",
"plot graph", "fit curve to cols", "transpose table", "split/join columns", "join rows/flatten columns",
"toggle display of row/column refs", "Hide/show column", "Narrow column", "Narrow table", "Fill empty cells",
"Insert vertical line", etc.
*org-dblock-write:tablefilter* is a dynamic block function which can be used for filtering the rows of a table into another one.
For more info about dynamic blocks see here: https://orgmode.org/manual/Dynamic-Blocks.html 

The *org-table-jump-next* & *org-table-jump-prev* commands provide a method for quickly & easily navigating
and altering tables. You can define arbitrary jump conditions which determine the sequence of cells visited
when *org-table-jump-next* is pressed repeatedly. There are many predefined ones in *org-table-jump-condition-presets*
which can be selected or altered ("edit preset"), or you can enter one manually ("enter manually").
These jump conditions are arbitrary lisp expressions that are evaluated at each cell to determine whether to move
there or not. The jump condition sexps can make use of locally defined functions in *org-table-filter-function-bindings*
which are also described in the docstring for *org-table-jump-condition*.
To change the jump condition, either use a C-u prefix arg with *org-table-jump-next*/*org-table-jump-prev* or 
call *org-table-set-jump-condition*. You can also select the order in which cells are checked by using a double C-u
prefix when calling *org-table-jump-next*/*org-table-jump-prev*, or by calling *org-table-set-jump-direction*.

The file *org-table-solve-mazelog.org* contains examples of how *org-table-jump* can be used to perform complex
tasks such as solving maze puzzles.

* Commands & keybindings

 Below is a complete list of commands:

  - *org-table-insert-or-delete-vline*
      Insert a vertical line in the current column, or delete some if NDELETE is non-nil.
  - *org-table-grab-columns*
     Copy/kill columns or region of table and return as list(s).
  - *org-table-flatten-columns* :
     Apply FN to next NROWS cells in selected columns and replace cells in current row with results.\\
  - *org-table-dispatch* :
     Do something with column(s) of org-table at point.\\
  - *insert-file-as-org-table* :
     Insert a file into the current buffer at point, and convert it to an org table.\\
  - *org-table-kill-field* :
     Kill the org-table field under point.\\
  - *org-table-copy-field* :
     Copy the org-table field under point to the kill ring.\\
  - *org-table-narrow-column*
     Split the current column of an org-mode table to be WIDTH characters wide.\\
  - *org-table-narrow*
     Narrow the entire org-mode table, apart from FIXEDCOLS, to be within WIDTH characters by adding new rows.\\
  - *org-table-fill-empty-cells*
     Fill empty cells in current column of org-table at point by splitting non-empty cells above them.\\
  - *org-table-query-dimension*
     Print and return the number of columns, data lines, cells, hlines, height & width (in chars) of org-table at point.\\
  - *org-table-move-cell*
     Prompt for a direction and move the current cell in that direction.\\
  - *org-table-show-jump-condition*
     Display a message in the minibuffer showing the current jump condition.\\
  - *org-table-set-jump-condition*
     Set the CONDITION for *org-table-jump-condition*.\\
  - *org-table-set-jump-direction*
     Set the DIRECTION for *org-table-jump-condition*; 'up, 'down, 'left or 'right.\\
  - *org-table-jump-next*
     Jump to the STEPS next field in the org-table at point matching *org-table-jump-condition*.\\
  - *org-table-jump-prev*
     Like *org-table-jump-next* but jump STEPS in opposite direction.\\
     
* Customizable Options

 Below is a list of customizable options:

   - *org-table-flatten-functions* :
    Alist of (NAME . FUNCTION) pairs for use with  - *org-table-flatten-column* :.\\
   - *org-table-graph-types* :
    List of graph types for  - *org-plot/gnuplot* :.\\
   - *org-table-dispatch-actions* :
    Actions that can be applied when  - *org-table-dispatch* : is called.\\
   - *org-table-filter-function-bindings* :
    Function bindings (with descriptions) used by *org-table-jump-condition* & *org-dblock-write:tablefilter*.\\
   - *org-table-jump-condition-presets*
    Named presets for *org-table-jump-condition*.\\
   - *org-table-timestamp-patterns*
    List of java style date-time matching patterns as accepted by *datetime-matching-regexp* and related functions.\\
   - *org-table-timestamp-format*
    Default format for timestamps output by *org-table-convert-timestamp*.\\
